apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: ticketing-v2-eks
  region: ap-south-1

managedNodeGroups:
  - name: ticketing-v2-workers
    instanceType: t3.small
    desiredCapacity: 1
    minSize: 1
    maxSize: 2
